server {
    server_name photos.raako.net;

    root /var/www/photos;

    index index.html index.htm index.php;

    # Cache images for 1 month
    location ~* \.(jpg|jpeg)$ {
       expires 30d;
       add_header Cache-Control "public";
    }

    # SPA routing - serve index.html for all routes
    location / {
       try_files $uri $uri/ /index.html;
    }

    location ~ /\.ht {
        deny all;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/photos.raako.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/photos.raako.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = photos.raako.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name photos.raako.net;
    listen 80;
    return 404; # managed by Certbot
}
